// Mocks generated by Mockito 5.4.6 from annotations
// in wordpal/test/providers/app_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:sqflite/sqflite.dart' as _i3;
import 'package:wordpal/models/saved_word.dart' as _i7;
import 'package:wordpal/models/word_entry.dart' as _i2;
import 'package:wordpal/services/database_service.dart' as _i6;
import 'package:wordpal/services/dictionary_service.dart' as _i4;
import 'package:wordpal/services/preferences_service.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWordEntry_0 extends _i1.SmartFake implements _i2.WordEntry {
  _FakeWordEntry_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabase_1 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DictionaryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDictionaryService extends _i1.Mock implements _i4.DictionaryService {
  @override
  _i5.Future<_i2.WordEntry> lookup(String? word) => (super.noSuchMethod(
        Invocation.method(
          #lookup,
          [word],
        ),
        returnValue: _i5.Future<_i2.WordEntry>.value(_FakeWordEntry_0(
          this,
          Invocation.method(
            #lookup,
            [word],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.WordEntry>.value(_FakeWordEntry_0(
          this,
          Invocation.method(
            #lookup,
            [word],
          ),
        )),
      ) as _i5.Future<_i2.WordEntry>);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i6.DatabaseService {
  @override
  _i5.Future<_i3.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i5.Future<_i3.Database>.value(_FakeDatabase_1(
          this,
          Invocation.getter(#database),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Database>.value(_FakeDatabase_1(
          this,
          Invocation.getter(#database),
        )),
      ) as _i5.Future<_i3.Database>);

  @override
  _i5.Future<int> insertWord(_i7.SavedWord? word) => (super.noSuchMethod(
        Invocation.method(
          #insertWord,
          [word],
        ),
        returnValue: _i5.Future<int>.value(0),
        returnValueForMissingStub: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i7.SavedWord>> getAllWords() => (super.noSuchMethod(
        Invocation.method(
          #getAllWords,
          [],
        ),
        returnValue: _i5.Future<List<_i7.SavedWord>>.value(<_i7.SavedWord>[]),
        returnValueForMissingStub:
            _i5.Future<List<_i7.SavedWord>>.value(<_i7.SavedWord>[]),
      ) as _i5.Future<List<_i7.SavedWord>>);

  @override
  _i5.Future<_i7.SavedWord?> getWord(String? word) => (super.noSuchMethod(
        Invocation.method(
          #getWord,
          [word],
        ),
        returnValue: _i5.Future<_i7.SavedWord?>.value(),
        returnValueForMissingStub: _i5.Future<_i7.SavedWord?>.value(),
      ) as _i5.Future<_i7.SavedWord?>);

  @override
  _i5.Future<int> updateMastery(
    int? id,
    bool? mastered,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMastery,
          [
            id,
            mastered,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
        returnValueForMissingStub: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> deleteWord(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteWord,
          [id],
        ),
        returnValue: _i5.Future<int>.value(0),
        returnValueForMissingStub: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<bool> isSaved(String? word) => (super.noSuchMethod(
        Invocation.method(
          #isSaved,
          [word],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [PreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferencesService extends _i1.Mock
    implements _i8.PreferencesService {
  @override
  _i5.Future<List<String>> getHistory() => (super.noSuchMethod(
        Invocation.method(
          #getHistory,
          [],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
        returnValueForMissingStub: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<void> addToHistory(String? word) => (super.noSuchMethod(
        Invocation.method(
          #addToHistory,
          [word],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearHistory() => (super.noSuchMethod(
        Invocation.method(
          #clearHistory,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> getPosFilter() => (super.noSuchMethod(
        Invocation.method(
          #getPosFilter,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #getPosFilter,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #getPosFilter,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> setPosFilter(String? filter) => (super.noSuchMethod(
        Invocation.method(
          #setPosFilter,
          [filter],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> getExamplesOnlyMode() => (super.noSuchMethod(
        Invocation.method(
          #getExamplesOnlyMode,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setExamplesOnlyMode(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setExamplesOnlyMode,
          [value],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
